<!DOCTYPE html>
<html>

<head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

</head>

<body>
<h1>Failed to confirm</h1>

<br>

<a href="http://localhost:8080/confirm/sendConfirmEmail/${confirmCode}">send another confirm email</a>

</body>

</html>